In [4]:

#exercise 1 Array creation
import numpy as np
arr1 = np.linspace(0,1,20)
print(f'linspace: {arr1.shape} , {type(arr1)}')

arr2 = np.eye(5)
print(f'identity: {arr2.shape} , {type(arr2)}')

arr3 = np.random.randint(1,100, size=(3,4))
print(f'rand_int: {arr3.shape} , {type(arr3)}')

linspace: (20,) , <class 'numpy.ndarray'>
identity: (5, 5) , <class 'numpy.ndarray'>
rand_int: (3, 4) , <class 'numpy.ndarray'>


In [5]:
#Exercise 2 Reshaping and flattening
arr = np.arange(1,25)
arr_3D = arr.reshape(2,3,4)
arr_2D = arr.reshape(6,4)
flattened = arr.flatten()
print(f'3_D : {arr_3D.shape}')
print(f'2_D: {arr_2D.shape}')
print(f'Flattened: {flattened.shape}')

3_D : (2, 3, 4)
2_D: (6, 4)
Flattened: (24,)


In [6]:
#exercise 3 Fancing Indexing & Boolean Masking
arr = np.random.rand(6,6)
every_row = arr[: : 2, : ]
print(f'every_row: {every_row.shape}')
arr_dia = np.diag(arr)
print(f'diangonal: {arr_dia.shape}')
out = np.where(arr > 0.7, 1, 0)
print(f'Binary matrix: {out.shape} , {out}')

every_row: (3, 6)
diangonal: (6,)
Binary matrix: (6, 6) , [[0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 1]
 [0 1 0 1 0 0]
 [0 1 0 0 0 1]
 [0 0 0 0 0 0]]


In [7]:
#Exercise 4 Slicing , Stacking & Splitting 
arr1 = np.random.rand(4,3)
arr2 = np.random.rand(4,3)
v_stack = np.vstack((arr1,arr2))
h_stack = np.hstack((arr1,arr2))
v_split = np.vsplit(v_stack,2)
h_split = np.hsplit(h_stack,2)
print(f'vstack: {v_stack.shape}')
print(f'hstack: {h_stack.shape}')
print(f'v_split equals arr1: {np.array_equal(h_split, arr1)}')
print(f'h_split equals arr1: {np.array_equal(h_split, arr1)}')

vstack: (8, 3)
hstack: (4, 6)
v_split equals arr1: False
h_split equals arr1: False


In [8]:
#Exercise 5 Boadcasting Intuition
arr1 = np.arange(1,5).reshape(4,1)
arr2 = np.arange(0,5).reshape(1,5)
print(f'{arr1.shape} + {arr2.shape} = {(arr1+arr2).shape}')
arr3 = np.arange(1,4).reshape(1,3)
arr4 = np.arange(1,13).reshape(4,3)
print(f'{arr3.shape} + {arr4.shape} = {(arr3+arr4).shape}')

(4, 1) + (1, 5) = (4, 5)
(1, 3) + (4, 3) = (4, 3)


In [9]:
#Exrecise 7 Z-Score Normalisation
arr = np.random.rand(100,5)
arr_mean = np.mean(arr, axis= 0)
arr_std = np.std(arr, axis= 0)
print(f'column mean: {arr_mean}')
print(f'column stds: {arr_std}')
# Exercise 8 Min-Max Scaling
arr_min = np.min(arr)


column mean: [0.48761724 0.54036742 0.53875048 0.44750641 0.51808796]
column stds: [0.29061687 0.32019358 0.28813682 0.30043607 0.28997905]


In [12]:
import time
arr_rand = np.random.rand(1000000)
start = time.time()
rand_sqr = np.sqrt(arr_rand)
numpy_time = time.time() - start
print(f'numpy time: ~{numpy_time}s')
start = time.time()
rand_sqr1 = [x**.5 for x in arr_rand]
loop_time = time.time() - start
print(f'Loop time: ~{loop_time}s')
speedup = (loop_time / numpy_time)
print(f'speedup: ~{speedup}s')

numpy time: ~0.012025594711303711s
Loop time: ~0.3075425624847412s
speedup: ~25.574000277562998s


In [14]:
#Exrecise 7 Z-Score Normalisation
arr = np.random.rand(100,5)
arr_mean = arr.mean(axis= 0)
arr_std = arr.std(axis= 0)
normalised = (arr - arr_mean)/arr_std
print(f'column mean: {np.round(normalised.mean(axis = 0), 2)}')
print(f'column std: {np.round(normalised.std(axis = 0), 2)}')


column mean: [-0. -0.  0.  0.  0.]
column std: [1. 1. 1. 1. 1.]
